=== mpue/JRhythm/resources/schema1.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="abstractScene" type="abstractScene"/>

  <xs:element name="defaultScene" type="defaultScene"/>

  <xs:complexType name="defaultScene">
    <xs:complexContent>
      <xs:extension base="abstractScene">
        <xs:sequence/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="abstractScene" abstract="true">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="rootNode" type="SceneNode" minOccurs="0"/>
      <xs:element name="currentCameraIndex" type="xs:int"/>
      <xs:element name="cameras" type="Camera" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="SceneNode" abstract="true">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="children" type="SceneNode" nillable="true" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="location" type="vector3F" minOccurs="0"/>
      <xs:element name="xrot" type="xs:float"/>
      <xs:element name="yrot" type="xs:float"/>
      <xs:element name="zrot" type="xs:float"/>
      <xs:element name="shaderProgramName" type="xs:string" minOccurs="0"/>
      <xs:element name="textureLocation" type="xs:string" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="vector3F">
    <xs:complexContent>
      <xs:extension base="vector">
        <xs:sequence>
          <xs:element name="x" type="xs:float"/>
          <xs:element name="y" type="xs:float"/>
          <xs:element name="z" type="xs:float"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="vector" abstract="true">
    <xs:sequence/>
  </xs:complexType>

  <xs:complexType name="Box">
    <xs:complexContent>
      <xs:extension base="SceneNode">
        <xs:sequence>
          <xs:element name="color" type="vector3F" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Plane">
    <xs:complexContent>
      <xs:extension base="SceneNode">
        <xs:sequence>
          <xs:element name="color" type="vector3F" minOccurs="0"/>
          <xs:element name="size" type="xs:float"/>
          <xs:element name="textureScale" type="xs:float"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Light">
    <xs:complexContent>
      <xs:extension base="SceneNode">
        <xs:sequence>
          <xs:element name="index" type="xs:int"/>
          <xs:element name="ambient" type="vector4F" minOccurs="0"/>
          <xs:element name="diffuse" type="vector4F" minOccurs="0"/>
          <xs:element name="specular" type="vector4F" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="vector4F">
    <xs:complexContent>
      <xs:extension base="vector">
        <xs:sequence>
          <xs:element name="x" type="xs:float"/>
          <xs:element name="y" type="xs:float"/>
          <xs:element name="z" type="xs:float"/>
          <xs:element name="w" type="xs:float"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="Camera">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0"/>
      <xs:element name="position" type="vector3F" minOccurs="0"/>
      <xs:element name="view" type="vector3F" minOccurs="0"/>
      <xs:element name="upVector" type="vector3F" minOccurs="0"/>
      <xs:element name="strafe" type="vector3F" minOccurs="0"/>
      <xs:element name="mode" type="mode" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="mode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FLY"/>
      <xs:enumeration value="FIRST_PERSON"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== mpue/JRhythm/resources/scene1.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<defaultScene  xsi:schemaLocation="schema1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <name>default</name>
    <rootNode>
        <name>root</name>        
        <children xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Light">
            <location>
                <x>500.2</x>
                <y>500.2</y>
                <z>500.2</z>
            </location>
            <xrot>0.0</xrot>
            <yrot>0.0</yrot>
            <zrot>0.0</zrot>
            <index>16385</index>
            <ambient>            	
                <x>1.0</x>
                <y>1.0</y>
                <z>1.0</z>
                <w>1.0</w>
            </ambient>
            <diffuse>
                <x>1.0</x>
                <y>1.0</y>
                <z>1.0</z>
                <w>1.0</w>
            </diffuse>
            <specular>
                <x>1.0</x>
                <y>1.0</y>
                <z>1.0</z>
                <w>1.0</w>
            </specular>
        </children>
        <children xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Plane">
            <location>
                <x>-100.0</x>
                <y>-1.0</y>
                <z>-100.0</z>
            </location>
            <xrot>0.0</xrot>
            <yrot>0.0</yrot>
            <zrot>0.0</zrot>
            <textureLocation>textures/tex1.png</textureLocation>
            <textured>true</textured>
            <size>200.0</size>
            <textureScale>4.0</textureScale>
        </children>
        <children xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Box">
            <name>box</name>
            <location>
                <x>0.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </location>
            <xrot>0.0</xrot>
            <yrot>0.0</yrot>
            <zrot>0.0</zrot>
            <textureLocation>textures/tex2.png</textureLocation>
            <textured>true</textured>
        </children>
        <children xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Box">
            <name>box</name>
            <location>
                <x>4.0</x>
                <y>0.0</y>
                <z>0.0</z>
            </location>
            <xrot>0.0</xrot>
            <yrot>15.0</yrot>
            <zrot>0.0</zrot>
            <textureLocation>textures/tex2.png</textureLocation>
            <textured>true</textured>
        </children>
        <children xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Box">
            <name>box</name>
            <location>
                <x>4.0</x>
                <y>0.0</y>
                <z>4.0</z>
            </location>
            <xrot>0.0</xrot>
            <yrot>65.0</yrot>
            <zrot>0.0</zrot>
            <textureLocation>textures/tex2.png</textureLocation>
            <textured>true</textured>
        </children>                 
        <location>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </location>
        <xrot>0.0</xrot>
        <yrot>0.0</yrot>
        <zrot>0.0</zrot>
    </rootNode>
    <currentCameraIndex>0</currentCameraIndex>
    <cameras>
        <name>cam1</name>
        <position>
            <x>0.0</x>
            <y>5.0</y>
            <z>-10.0</z>
        </position>
        <view>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </view>
        <upVector>
            <x>0.0</x>
            <y>1.0</y>
            <z>0.0</z>
        </upVector>
        <strafe>
            <x>-1.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </strafe>
        <mode>FLY</mode>
    </cameras>
    <cameras>
        <name>cam2</name>
        <position>
            <x>0.0</x>
            <y>5.0</y>
            <z>-10.0</z>
        </position>
        <view>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </view>
        <upVector>
            <x>0.0</x>
            <y>1.0</y>
            <z>0.0</z>
        </upVector>
        <strafe>
            <x>-1.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </strafe>
        <mode>FLY</mode>
    </cameras>
    <cameras>
        <name>cam3</name>
        <position>
            <x>0.0</x>
            <y>5.0</y>
            <z>-10.0</z>
        </position>
        <view>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </view>
        <upVector>
            <x>0.0</x>
            <y>1.0</y>
            <z>0.0</z>
        </upVector>
        <strafe>
            <x>-1.0</x>
            <y>0.0</y>
            <z>0.0</z>
        </strafe>
        <mode>FLY</mode>
    </cameras>
</defaultScene>
